# -*- coding: utf-8 -*-
"""20210204033.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGbkkl6ahoXGa-VzdZYHgRW7WInzkt0R

# **1. Understanding the Dataset**
"""

# Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Set random seed for reproducibility
np.random.seed(42)

data = pd.read_csv("/content/health_data.csv")

data.head()

# Let's examine the dataset
print(data.shape)

# Load the Cardiovascular dataset
X = data[['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']]
y = data[['cardio']]

"""
# **2. Data Preprocessing**"""

# Examine the data
print("\nFirst 5 rows:")
print(X.head())

# Check for missing values
print("\nMissing values:")
print(X.isnull().sum().sum())

# Statistical summary
print("\nStatistical summary:")
print(X.describe())

# Since our dataset is already numeric, we don't need to handle categorical features
# Let's check for highly correlated features
plt.figure(figsize=(8, 6))
correlation_matrix = X.corr()
sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm')
plt.title('Feature Correlation Matrix')
plt.show()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Standardize the features (important for KNN)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

"""# **3. Model Training - Decision Tree**"""

# Initialize and train the Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Make predictions
y_pred_dt = dt_model.predict(X_test)

# Evaluate the model
dt_accuracy = accuracy_score(y_test, y_pred_dt)
dt_precision = precision_score(y_test, y_pred_dt)
dt_recall = recall_score(y_test, y_pred_dt)
dt_f1 = f1_score(y_test, y_pred_dt)

print("\nDecision Tree Model Evaluation:")
print(f"Accuracy: {dt_accuracy:.4f}")
print(f"Precision: {dt_precision:.4f}")
print(f"Recall: {dt_recall:.4f}")
print(f"F1 Score: {dt_f1:.4f}")

# Confusion Matrix
dt_cm = confusion_matrix(y_test, y_pred_dt)
plt.figure(figsize=(8, 6))
sns.heatmap(dt_cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Disease', 'Disease'],
            yticklabels=['No Disease', 'Disease'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Decision Tree Confusion Matrix')
plt.show()

"""# **4. Model Training - K-Nearest Neighbors (KNN)**"""

# Initialize and train the KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test_scaled)

# Evaluate the model
knn_accuracy = accuracy_score(y_test, y_pred_knn)
knn_precision = precision_score(y_test, y_pred_knn)
knn_recall = recall_score(y_test, y_pred_knn)
knn_f1 = f1_score(y_test, y_pred_knn)

print("\nKNN Model Evaluation:")
print(f"Accuracy: {knn_accuracy:.4f}")
print(f"Precision: {knn_precision:.4f}")
print(f"Recall: {knn_recall:.4f}")
print(f"F1 Score: {knn_f1:.4f}")

# Confusion Matrix
knn_cm = confusion_matrix(y_test, y_pred_knn)
plt.figure(figsize=(8, 6))
sns.heatmap(knn_cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Disease', 'Disease'],
            yticklabels=['No Disease', 'Disease'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('KNN Confusion Matrix')
plt.show()

"""# **5. Model Comparison**"""

# Compare both models
print("\nModel Comparison:")
print(f"Decision Tree F1 Score: {dt_f1:.4f}")
print(f"KNN F1 Score: {knn_f1:.4f}")

if dt_f1 > knn_f1:
    print("Decision Tree performs better in terms of F1 score.")
else:
    print("KNN performs better in terms of F1 score.")

# Classification Report for Decision Tree
print("\nDecision Tree Classification Report:")
print(classification_report(y_test, y_pred_dt, target_names=['No Disease', 'Disease']))

print("\nKNN Classification Report:")
print(classification_report(y_test, y_pred_knn, target_names=['No Disease', 'Disease']))

